# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - 'src/**/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SCCACHE_GHA_ENABLED: "true"

permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
    
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Install LLVM and Clang
        run: sudo wget -qO- https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.3/LLVM-19.1.3-Linux-X64.tar.xz | tar -xJf - && export PATH=$PWD/LLVM-19.1.3-Linux-X64/bin:$PATH
        
      - name: Install dependencies
        run: npm ci

      - name: Compile wasm
        run: npm run build-wasm-all

      - name: Build
        run: npm run build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deploy
          FOLDER: test_dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
